services:
  applicant-nginx:
    container_name: applicant-nginx
    build:
      context: .
      dockerfile: ./docker/aws/nginx/Dockerfile
    volumes:
      - /home/bizmatesph-joselin/projects/bizmates.ph:/home/bizmates/bizmates.ph/
  applicant-php-fpm:
    container_name: applicant-php-fpm
    build:
      context: ./
      dockerfile: ./docker/aws/php/Dockerfile
    volumes:
      - /home/bizmatesph-joselin/projects/bizmates.ph:/home/bizmates/bizmates.ph/
networks:
  default:
    name: ph-finance
    external: true
