services:
  bco-mysql:
    image: mysql:8.0.28
    container_name: bco-mysql
    ports:
      - 3313:3306
    environment:
      MYSQL_ROOT_PASSWORD: Bizmates2016!
      MYSQL_USER: bizmates
      MYSQL_PASSWORD: Bizmates2016!
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  default:
    name: ph-finance
    external: true
