services:
  bizmates-gateway:
    container_name: bizmates-gateway
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      # Render Nginx Configuration
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/conf.d/sites-enabled
      # Bizmates JP SSL Certificate
      - ./certs/bizmates.jp/bizmates.jp.local.crt:/bizmates.jp/ssl/certs/bizmates.jp.local.crt
      - ./certs/bizmates.jp/bizmates.jp.local.key:/bizmates.jp/ssl/keys/bizmates.jp.local.key
      # Bizmates JP
      - /home/joselin-bizmatesph/projects/portal/bizmates.jp:/home/bizmates/bizmates.jp
      # Bizmates PH
      - /home/joselin-bizmatesph/projects/portal/bizmates.ph:/home/bizmates/bizmates.ph
      # FMS
      - /home/bizmatesph-joselin/projects/fms/bizmates-finance-app/dist:/fms-frontend
      # MBTI Frontend
      - /home/bizmatesph-joselin/projects/student/MBTI_frontend/dist:/student-frontend
      # Mystage
      - /home/bizmatesph-joselin/projects/mystage/mystage-frontend/dist:/mystage-student
      - /home/bizmatesph-joselin/projects/mystage/mystage-frontend/dist:/mystage-jp
      # Mystage System Test
      - /home/bizmatesph-joselin/projects/mystage/mystage-system-test/dist:/mystage-system-test
networks:
  default:
    name: ph-finance
    external: true
