services:
  bizmates-mailer:
    image: public.ecr.aws/supabase/mailpit:v1.22.3
    restart: unless-stopped
    container_name: bizmates-mailer
  bizmates-redis:
    image: redis:5-alpine
    container_name: bizmates-redis
  bizmates-s3:
    image: minio/minio:RELEASE.2020-08-27T05-16-20Z
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=MINIO_SECRET_KEY
    container_name: bizmates-s3
    volumes:
      - "./bizmates-s3:/tmp/s3_data"
    ports:
      - 9089:80
    command: "minio server --address :80 /tmp/s3_data"
networks:
  default:
    name: ph-finance
    external: true
